### ISSUE TITLE
Add support to rename files in the current folder

### ISSUE THREAD

**Issue by ryanhex53** [rtomrud/tagtoname#13]
I tried the following commands, but none of them worked:

* `npx tagtoname .`
* `npx tagtoname .\*`
* `npx tagtoname ./*`
* `npx tagtoname *`

Please help me figure out what I'm doing wrong.

**Comment by ryanhex53** [comment]
this is also not work in windows.
```
Z:\>npx tagtoname -n liyang/*
liyang/*: ENOENT: no such file or directory, stat 'Z:\liyang\*'
```

**Comment by rtomrud** [comment]
You can now use glob patterns to rename files in the current folder:

```bash
npx tagtoname *
npx tagtoname **/* # Renames files in subfolders too
```
